version: '3'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kp-client
    hostname: kp-client
    restart: always
    env_file: .env
    environment:
      - APP_API=$APP_API
    ports:
      - "3005:3005"
    networks:
      - kpClient

networks:
  kpClient:
