export default (data) => {
  return `<?xml version="1.0" encoding="windows-1250"?>
    <MoneyData>
      <UpdateHd>1</UpdateHd>
      <SeznamFirem>
        <Firma>
          <GUID>{13FE548C-1A7C-4896-B648-1AF094AA8492}</GUID>
          <Nazev>${data.firmInfo[0].nameCompany}</Nazev>
          <Adresa>
            <Ulice>${data.address}</Ulice>
            <Misto>${data.city}</Misto>
            <PSC>${data.zip}</PSC>
            <Stat>${data.state}</Stat>
            <KodStatu>CZ</KodStatu>
          </Adresa>
          <ObchNazev>${data.firmInfo[0].nameCompany}</ObchNazev>
          <ObchAdresa>
            <Ulice>${data.address}</Ulice>
            <Misto>${data.city}</Misto>
            <PSC>${data.zip}</PSC>
            <Stat>${data.state}</Stat>
            <KodStatu>CZ</KodStatu>
          </ObchAdresa>
          <FaktNazev>${data.firmInfo[0].nameCompany}</FaktNazev>
          <FaktAdresa>
            <Ulice>${data.address}</Ulice>
            <Misto>${data.city}</Misto>
            <PSC>${data.zip}</PSC>
            <Stat>${data.state}</Stat>
            <KodStatu>CZ</KodStatu>
          </FaktAdresa>
          <Mobil>
            <Pred>+420</Pred>
            <Cislo>${data.phone}</Cislo>
          </Mobil>
          <EMail>${data.email}</EMail>
          <ICO>${data.firmInfo[0].ico}</ICO>
          <DIC>${data.firmInfo[0].dic}</DIC>
          <eshop>
            <IN_Export>6</IN_Export>
          </eshop>
          <Osoba>
            <Jmeno>${data.name}</Jmeno>
            <Prijmeni>${data.surname}</Prijmeni>
            <Jednatel>1</Jednatel>
          </Osoba>
        </Firma>
      </SeznamFirem>
      <SeznamObjPrij>
        <ObjPrij>
          <Popis>Objedn�vka z e-shopu (${data.id})</Popis>
          <Poznamka>${data.description}</Poznamka>
          <!-- 
          <Vystaveno>2010-06-01</Vystaveno>
          <Vyridit_do>2010-06-10/Vyridit_do> 
          -->
          <DodOdb>
            <GUID>{13FE548C-1A7C-4896-B648-1AF094AA8492}</GUID>
          </DodOdb>
          <KPFromOdb>1</KPFromOdb>
          <PlatPodm>${data.payment.name}</PlatPodm>
          <Doprava>${data.delivery.name}</Doprava>
          <PrimDoklad>${data.id}</PrimDoklad>
          <Sleva>0</Sleva>
          <eshop>
            <IN_Export>6</IN_Export>
            <IN_Poznamk>${data.description}</IN_Poznamk>
          </eshop>
        ${data.basketItem.map(item => `
          <Polozka>
            <PocetMJ>${item.count}</PocetMJ>
            <Cena>${item.price}</Cena>
            <SazbaDPH>21</SazbaDPH>
            <TypCeny>1</TypCeny>
            <Sleva>0</Sleva>
            <!--
            <Vystaveno>2010-06-01</Vystaveno>
            <Vyridit_do>2010-06-10</Vyridit_do>
            -->
            <CenovaHlad>Z�kladn�</CenovaHlad>
            <CenaPoSleve>1</CenaPoSleve>
            <KmKarta>
              <GUID>${item.guid}</GUID>
            </KmKarta>
            <Sklad>
              <GUID>{504C55C5-461E-46C4-A42B-5242FDE76A03}</GUID>
            </Sklad>
          </Polozka>
        `)}
          <Polozka>
            <Popis>Doprava</Popis>
            <PocetMJ>1</PocetMJ>
            <ZbyvaMJ>1</ZbyvaMJ>
            <Cena>${data.delivery.value}</Cena>
            <SazbaDPH>21</SazbaDPH>
            <TypCeny>1</TypCeny>
            <Sleva>0</Sleva>
            <!--
            <Vystaveno>2010-06-01</Vystaveno>
            <Vyridit_do>2010-06-10</Vyridit_do>
            -->
            <CenaPoSleve>1</CenaPoSleve>
            - <NesklPolozka>
              <TypZarDoby>N</TypZarDoby>
            </NesklPolozka>
          </Polozka>
          <Polozka>
            <Popis>Platba</Popis>
            <PocetMJ>1</PocetMJ>
            <ZbyvaMJ>1</ZbyvaMJ>
            <Cena>${data.payment.value}</Cena>
            <SazbaDPH>21</SazbaDPH>
            <TypCeny>1</TypCeny>
            <Sleva>0</Sleva>
            <!--
            <Vystaveno>2010-06-01</Vystaveno>
            <Vyridit_do>2010-06-10</Vyridit_do>
            -->
            <CenaPoSleve>1</CenaPoSleve>
            - <NesklPolozka>
              <TypZarDoby>N</TypZarDoby>
            </NesklPolozka>
          </Polozka>
        </ObjPrij>
      </SeznamObjPrij>
    </MoneyData>`
}